language: python
sudo: true
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-cs language-pack-cs
python: 3.6
cache: pip
env:
  - TOXENV="flake8"
  - TOXENV="isort"
  - TOXENV="py36"
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
