#!/bin/bash

set -e

if [ $# != 1 ]; then
    echo >&2 "Usage: $0 <service>"
    exit 1
fi

SERVICE=$1
DATE=$(date '+%Y%m%d-%H%M')

sudo docker compose stop $SERVICE
sudo tar -czf $SERVICE-$DATE.tar.gz $SERVICE/
sudo docker compose start $SERVICE
