version: '3.4'
services:

  leprikon:
    image: leprikon/leprikon:testing
    depends_on:
      - db
      - memcached
    environment:
      DEBUG: TEMPLATE
      SECRET_KEY: secretkey
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: leprikon
      DATABASE_PASSWORD: leprikonpassword
      DATABASE_USER: leprikon
      MEMCACHED_LOCATION: memcached:11211
    ports:
      - 127.0.0.1:8000:80
    restart: unless-stopped
    volumes:
      - ./leprikon:/app/leprikon:z
      - ./leprikon_tests:/app/leprikon_tests:z
      - ./bin:/app/bin:z
      - ./conf:/app/conf:z
      - ./data:/app/data:z
      - ./htdocs/media:/app/htdocs/media:z
      - db:/var/run/mysqld:z

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: leprikon
      MYSQL_PASSWORD: leprikonpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: leprikon
    restart: unless-stopped
    volumes:
      - db:/var/run/mysqld:z
      - ./mysql:/var/lib/mysql:z

  memcached:
    image: memcached
    ports:
      - 127.0.0.1:11211:11211
    restart: unless-stopped

volumes:
  db:
