version: '3.4'
services:

  leprikon:
    image: leprikon/leprikon:latest
    build: .
    depends_on:
      - memcached
      - mysql
      - smtp
    environment:
      SECRET_KEY: SECRET_KEY
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: leprikon
      DATABASE_USER: leprikon
      DATABASE_PASSWORD: DATABASE_PASSWORD
      EMAIL_HOST: smtp
      EMAIL_HOST_USER: leprikon
      EMAIL_HOST_PASSWORD: EMAIL_HOST_PASSWORD
      EMAIL_SUBJECT_PREFIX: '[Leprikón]'
      MEMCACHED_LOCATION: memcached:11211
      SERVER_EMAIL: '"Leprikón <leprikon@leprikon.cz>"'
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./data:/app/data
      - ./media:/app/htdocs/media
      - mysql:/var/run/mysqld

  memcached:
    image: memcached

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: leprikon
      MYSQL_USER: leprikon
      MYSQL_PASSWORD: DATABASE_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: leprikon.cz
      smtp_user: leprikon:EMAIL_HOST_PASSWORD
    stdin_open: true
    tty: true
    volumes:
    - ./dkim:/etc/opendkim/domainkeys

volumes:
  mysql:
