version: "3.4"
services:
  leprikon:
    image: leprikon/leprikon:latest
    build: .
    command: leprikon runserver 0:80
    depends_on:
      - postgres
      - redis
    environment:
      # DEBUG: EMAIL,TEMPLATE,DB
      DEBUG: EMAIL,TEMPLATE
      DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      DATABASE_HOST: /var/run/postgresql
      DATABASE_NAME: leprikon
      DATABASE_USER: leprikon
      DATABASE_PASSWORD: POSTGRES_PASSWORD
      EMAIL_SUBJECT_PREFIX: "[Leprikón]"
      LEPRIKON_URL: http://leprikon.localhost
      CACHE_LOCATION: unix:///var/run/redis/redis.sock
      SECRET_KEY: SECRET_KEY
      SERVER_EMAIL: '"Leprikón <leprikon@leprikon.cz>"'
      CMSPLUGIN_FILER_MIGRATED: yes
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/app/data
      - ./leprikon:/app/leprikon
      - ./media:/app/htdocs/media
      - postgres:/var/run/postgresql
      - redis:/var/run/redis

  redis:
    image: redis
    command: bash -c "chmod 0777 /var/run/redis && redis-server --appendonly yes --unixsocket /var/run/redis/redis.sock --unixsocketperm 777"
    volumes:
      - ./redis:/data
      - redis:/var/run/redis

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: leprikon
      POSTGRES_USER: leprikon
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    volumes:
      - postgres:/var/run/postgresql
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres:
  redis:
