#!/bin/bash

set -e

if [ $# != 1 ]; then
    echo >&2 "Usage: $0 <backup-file>"
    exit 1
fi

BACKUP="$1"
SERVICE="$(basename "$BACKUP" | sed -s 's/-.*//')"
DATE=$(date '+%Y%m%d-%H%M')

sudo docker compose stop $SERVICE
test -d $SERVICE && mv $SERVICE $SERVICE-$DATE
sudo tar -xzf $BACKUP
sudo docker compose start $SERVICE
