# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_subjecttype_plural_akuzativ(apps, schema_editor):
    SubjectType = apps.get_model('leprikon', 'SubjectType')
    SubjectType.objects.update(plural_akuzativ=models.F('plural'))


class Migration(migrations.Migration):

    dependencies = [
        ('leprikon', '0054_registration_dates_by_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttype',
            name='plural_akuzativ',
            field=models.CharField(blank=True, max_length=150, verbose_name='name (plural, akuzativ)'),
        ),
        migrations.RunPython(set_subjecttype_plural_akuzativ),
    ]
