name: leprikon BE CI

on: 
  push:
    paths:
      - 'leprikon/**'
      - 'leprikon_tests/**'
      - '.github/workflows/CI.yml'
jobs:
  tests:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: test_db
      redis:
        image: redis:alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git python3-pip
          python3 -m pip install --upgrade pip poetry
          poetry install --with dev
      - name: Run tests
        run: poetry run tox --colored=yes --current-env
        env:
          DATABASE_URL: postgres://django:django@postgres:5432/test_db
          CACHE_URL: redis://redis:6379
